openapi: 3.1.0
info:
  title: Farm Management API (MVP)
  version: 0.1.0
servers:
  - url: http://localhost:3001/api
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /farms:
    get:
      summary: List farms
      responses:
        '200': { description: OK }
    post:
      summary: Create farm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                location: { type: string }
              required: [name]
      responses:
        '201': { description: Created }
  /fields:
    get:
      summary: List fields
      responses:
        '200': { description: OK }
  /tasks:
    get:
      summary: List tasks
      responses:
        '200': { description: OK }
